# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPU_usage', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Anything',
        ),
    ]
