# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwdata', '0002_auto_20160712_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='CPU_usage',
            field=models.FloatField(),
        ),
    ]
