# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwdata', '0003_auto_20160712_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='SWAP_usage',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
